# This file was generated by GoReleaser. DO NOT EDIT.
cask "tash" do
  name "tash"
  desc "AI-powered fish shell assistant; type naturally, get commands"
  homepage "https://github.com/renjfk/tash"
  version "0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
      "fish",
    ]

  on_macos do
    on_intel do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Darwin_x86_64"
      sha256 "2acc9e63d426af9e188a0140509f7edeb36430232a0ee952a68f7d0f0a58d9df"
      binary "tash_Darwin_x86_64", target: "tash"
    end
    on_arm do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Darwin_arm64"
      sha256 "21a12a8957c0c93b6d1e72d3ac2ceabc44a345651ed7071e31e0b07e394bc25c"
      binary "tash_Darwin_arm64", target: "tash"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Linux_x86_64"
      sha256 "a18de490bcd1f7c1e439ddbd013eff3f9678e7ed84a669326576f0f6220c498c"
      binary "tash_Linux_x86_64", target: "tash"
    end
    on_arm do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Linux_arm64"
      sha256 "87486a2ffb1d2fe87670cf6e85af36f0f6aa4c91981f95f53fef0be865845782"
      binary "tash_Linux_arm64", target: "tash"
    end
  end

  caveats do
    "Run 'tash init' after setting your API key:"
    "  export ANTHROPIC_API_KEY=your-key"
    "  tash init"
  end

  # No zap stanza required
end
