# This file was generated by GoReleaser. DO NOT EDIT.
cask "tash" do
  name "tash"
  desc "AI-powered fish shell assistant; type naturally, get commands"
  homepage "https://github.com/renjfk/tash"
  version "0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on formula: [
      "fish",
    ]

  on_macos do
    on_intel do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Darwin_x86_64"
      sha256 "bcbb4df5fab65ade249f14f2d3a807c319cc8e58465a5ad791656adddcacb3ba"
      binary "tash_Darwin_x86_64", target: "tash"
    end
    on_arm do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Darwin_arm64"
      sha256 "13d3f96d2d03be01647e9a7f152e3c09488c94e1715706926bed2159d1184286"
      binary "tash_Darwin_arm64", target: "tash"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Linux_x86_64"
      sha256 "edb7cd1128959befdeececc99cb19f36ba495a209f00922ec89b038127ffbbc6"
      binary "tash_Linux_x86_64", target: "tash"
    end
    on_arm do
      url "https://github.com/renjfk/tash/releases/download/v#{version}/tash_Linux_arm64"
      sha256 "71691539fb0458b13094d08474e573264f7e10c855d4740620b610deddf317ac"
      binary "tash_Linux_arm64", target: "tash"
    end
  end

  caveats do
    "Run 'tash init' after setting your API key:"
    "  export ANTHROPIC_API_KEY=your-key"
    "  tash init"
  end

  # No zap stanza required
end
